name: flutter_animated_bubble_background
description: "A Flutter package that provides an animated background widget with floating bubbles and customizable gradient colors. Perfect for creating engaging and beautiful app backgrounds."
version: 0.0.2
homepage: https://github.com/GianSandoval5/flutter_animated_bubble_background
repository: https://github.com/GianSandoval5/flutter_animated_bubble_background
issue_tracker: https://github.com/GianSandoval5/flutter_animated_bubble_background/issues
documentation: https://github.com/GianSandoval5/flutter_animated_bubble_background#readme

topics:
  - ui
  - animation
  - background
  - bubbles
  - gradient

screenshots:
  - description: 'Purple Galaxy gradient with animated bubbles'
    path: assets/purpleGalaxyGradient.png
  - description: 'Tropical Sunset gradient theme'
    path: assets/tropicalSunsetGradient.png
  - description: 'Deep Ocean blue gradient'
    path: assets/deepOceanGradient.png

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

license: MIT